#pragma once
#include <vector>
#include <string>

// English word lists, organised by difficulty tier.
// Easy: 3-4 letter words
// Medium: 4-6 letter words
// Hard: 5-8 letter words
// All words to be lowercase

namespace WordList
{
    // Easy: short, common words
    static const std::vector<std::string> EASY = {
        "cat", "dog", "hen", "pig", "cow", "fox", "owl", "bat", "ant", "bee",
        "car", "bus", "van", "map", "bag", "cup", "hat", "bed", "box", "log",
        "sun", "sky", "sea", "ice", "egg", "arm", "eye", "ear", "lip", "rib",
        "book", "ball", "bell", "bird", "boat", "cake", "call", "card", "coat",
        "door", "duck", "farm", "fish", "flag", "frog", "game", "gate", "gift",
        "girl", "goat", "gold", "good", "hand", "hill", "home", "horn", "jump",
        "keep", "kick", "king", "kite", "lamp", "land", "leaf", "left", "life",
        "lime", "list", "lock", "loop", "loss", "loud", "love", "luck", "milk",
        "mind", "mine", "mint", "miss", "moon", "more", "most", "moth", "move",
        "nail", "name", "neck", "nest", "news", "next", "note", "open", "oven",
        "park", "path", "pick", "pile", "pine", "pink", "pipe", "plan", "play",
        "plot", "plug", "pond", "pool", "poor", "post", "pull", "pump", "push",
        "rain", "read", "rest", "rice", "rich", "ride", "ring", "road", "rock",
        "roll", "roof", "room", "rope", "rose", "rule", "rush", "rust", "safe",
        "sail", "sale", "salt", "sand", "save", "seed", "self", "sell", "shed",
        "ship", "shoe", "shop", "shut", "sign", "silk", "sing", "sink", "site",
        "size", "skin", "skip", "slab", "slip", "slow", "slug", "snap", "snow",
        "sock", "soft", "soil", "solo", "some", "song", "sore", "soup", "sour",
        "spin", "spot", "star", "stay", "stem", "step", "stir", "stop", "stub",
        "such", "suit", "swap", "swim", "tail", "take", "talk", "tall", "tank",
        "tape", "task", "tent", "term", "test", "text", "than", "then", "thin",
        "this", "tide", "tile", "till", "time", "toad", "told", "toll", "tomb",
        "tool", "toss", "tour", "town", "tree", "trim", "trip", "true", "tube",
        "tuck", "tuft", "tusk", "twin", "twig", "type", "unit", "upon", "used",
        "vane", "vary", "vast", "veil", "very", "view", "vine", "vole", "vote",
        "wage", "wake", "walk", "wall", "wand", "warm", "wart", "wash", "wasp",
        "wave", "weed", "week", "well", "went", "west", "when", "whip", "wide",
        "wild", "will", "wind", "wine", "wing", "wink", "wire", "wish", "with",
        "woke", "wolf", "wood", "wool", "word", "wore", "work", "worm", "wrap",
        "wren", "hay", "yawn", "year", "yell", "your", "zero", "zone", "zoom"
    };

    // Medium: slightly longer or less common words
    static const std::vector<std::string> MEDIUM = {
        "about", "above", "after", "again", "agree", "ahead", "album", "algae",
        "align", "alike", "alive", "alley", "allow", "aloud", "altar", "angel",
        "angle", "angry", "ankle", "annex", "apple", "apply", "apron", "arise",
        "arson", "aside", "asked", "aspen", "asset", "atlas", "attic", "audio",
        "badge", "baker", "banjo", "barge", "baron", "basil", "basin", "basis",
        "beach", "bingo", "black", "blade", "blame", "bland", "blank", "blast",
        "blaze", "bleed", "blend", "bless", "blind", "block", "blood", "bloom",
        "blown", "board", "bonus", "boots", "bough", "brace", "brain", "brake",
        "brand", "brave", "bread", "break", "breed", "brick", "bride", "brief",
        "bring", "brisk", "brook", "brush", "build", "built", "burst", "buyer",
        "cabin", "cable", "camel", "canal", "candy", "cargo", "carol", "carry",
        "cause", "chain", "chair", "chalk", "charm", "chase", "cheap", "check",
        "cheek", "chess", "chest", "chief", "child", "china", "choir", "chunk",
        "civic", "civil", "claim", "clamp", "class", "claw", "clean", "clear",
        "clerk", "click", "cliff", "climb", "cling", "clock", "clone", "close",
        "cloud", "coach", "coast", "cocoa", "comet", "comic", "coral", "could",
        "count", "court", "cover", "covet", "craft", "crane", "crash", "cream",
        "creek", "crest", "crisp", "cross", "crowd", "crown", "cruel", "crush",
        "crust", "curve", "cycle", "daily", "dance", "datum", "dealt", "debut",
        "decay", "decoy", "delta", "dense", "depot", "depth", "derby", "devil",
        "diary", "ditch", "divan", "dizzy", "dodge", "doing", "donor", "doubt",
        "dough", "dowry", "draft", "drain", "drama", "drawn", "dream", "dress",
        "drift", "drill", "drink", "drive", "drool", "drove", "drown", "druid",
        "dryer", "dwarf", "eagle", "early", "earth", "eight", "elect", "elite",
        "ember", "empty", "enemy", "enjoy", "enter", "entry", "equal", "equip",
        "error", "essay", "event", "every", "exact", "exert", "exile", "extra",
        "fable", "faced", "facto", "fairy", "faith", "false", "fancy", "fauna",
        "feast", "fence", "ferry", "fetch", "fever", "fewer", "fibre", "field",
        "fiend", "fifth", "fifty", "fight", "final", "first", "fixed", "flame",
        "flank", "flash", "flask", "fleet", "flesh", "float", "flock", "flood",
        "floor", "flora", "flour", "flute", "focus", "foliage", "force", "forge",
        "found", "frame", "frank", "fraud", "fresh", "front", "frost", "fruit",
        "fully", "fungi", "funny", "gauge", "gavel", "ghost", "glade", "gland",
        "glare", "glass", "gleam", "glide", "gloom", "glory", "glove", "glued",
        "gnome", "gorge", "gourd", "grace", "grade", "grain", "grand", "grant",
        "grasp", "grass", "grave", "greed", "green", "greet", "grief", "grill",
        "grind", "groan", "grope", "gross", "group", "grove", "grown", "gruel",
        "guide", "guild", "guile", "guilt", "guise", "gusto", "gypsy", "habit",
        "harsh", "hatch", "haunt", "haven", "heart", "heavy", "hence", "herbs",
        "hinge", "hippo", "holly", "honey", "horse", "hotel", "house", "human",
        "humid", "hurry", "hyena", "ideal", "image", "imply", "inbox", "index",
        "indie", "ingot", "inlet", "inner", "input", "inter", "infer", "ionic",
        "issue", "ivory", "jewel", "joust", "judge", "juice", "juicy", "juice",
        "karma", "knack", "kneel", "knife", "knock", "knoll", "knots", "koala",
        "label", "lance", "large", "laser", "latch", "later", "lathe", "layer",
        "learn", "lease", "leech", "legal", "lemon", "level", "light", "lilac",
        "limit", "linen", "liver", "liver", "local", "lodge", "logic", "loose",
        "lover", "lower", "loyal", "lucid", "lunar", "lunch", "lusty", "magic",
        "major", "maker", "manor", "march", "marsh", "match", "maths", "mayor",
        "media", "mercy", "merge", "merit", "metal", "metre", "minor", "minus",
        "mirth", "mitre", "model", "money", "month", "moral", "motor", "mould",
        "mount", "mouse", "mouth", "movie", "mulch", "music", "muted", "myrrh",
        "naive", "naval", "nerve", "never", "night", "noise", "north", "notch",
        "novel", "nurse", "nymph", "occur", "offer", "olive", "onset", "opera",
        "orbit", "order", "other", "outer", "oxide", "ozone", "paced", "paddy",
        "paint", "panel", "panic", "paper", "patch", "pause", "peace", "pearl",
        "pedal", "penny", "peril", "perch", "petal", "petty", "phase", "photo",
        "piano", "piece", "pilot", "pitch", "pixel", "pixel", "pizza", "place",
        "plain", "plane", "plant", "plate", "plaza", "plead", "pleat", "pluck",
        "plume", "plump", "plunge", "point", "poise", "polar", "polyp", "poppy",
        "porch", "pouch", "pound", "power", "price", "pride", "prime", "print",
        "prior", "prize", "probe", "prone", "proof", "prose", "proud", "prove",
        "prune", "psalm", "pulse", "pupil", "purse", "queen", "query", "queue",
        "quick", "quiet", "quota", "quote", "rabbi", "radar", "radio", "rally",
        "raven", "razor", "reach", "realm", "rebel", "refer", "reign", "relax",
        "repay", "resin", "revel", "ridge", "rifle", "right", "rigid", "rivet",
        "robin", "rouge", "rough", "round", "route", "rover", "rowdy", "royal",
        "ruler", "rupee", "rural", "sadly", "saint", "salve", "sauce", "scale",
        "scare", "scene", "scone", "scoop", "score", "scout", "screw", "scrub",
        "seize", "sense", "serum", "seven", "shard", "share", "shark", "sharp",
        "shelf", "shell", "shift", "shine", "shirt", "shock", "shore", "short",
        "shout", "shove", "shrew", "sight", "since", "sixth", "sixty", "skill",
        "skull", "skunk", "slate", "slave", "sleep", "sleet", "slept", "slice",
        "slide", "slime", "slope", "smart", "smell", "smile", "smoke", "snail",
        "snake", "snare", "sneak", "snore", "solar", "solid", "solve", "south",
        "space", "spade", "spare", "spark", "spawn", "speak", "spear", "speed",
        "spend", "spice", "spill", "spine", "spite", "split", "spoke", "spore",
        "sport", "spray", "spree", "sprig", "squad", "squat", "squid", "stack",
        "staff", "stage", "stain", "stale", "stall", "stand", "stare", "stark",
        "start", "state", "steam", "steel", "steep", "steer", "stern", "stick",
        "stiff", "still", "stock", "stone", "stood", "store", "storm", "story",
        "stout", "stove", "strap", "straw", "stray", "strip", "study", "style",
        "sugar", "suite", "swamp", "swarm", "swear", "sweep", "sweet", "swept",
        "swift", "sword", "sworn", "synth", "syrup", "table", "talon", "tapir",
        "taste", "teach", "tears", "teeth", "tempo", "tense", "tenth", "theft",
        "their", "theme", "there", "these", "thick", "thing", "think", "thorn",
        "those", "three", "threw", "throw", "thrum", "thumb", "tiara", "tiger",
        "tight", "tilted", "timer", "tired", "title", "toast", "token", "tonic",
        "tooth", "topaz", "topic", "torch", "total", "totem", "touch", "tough",
        "towel", "tower", "toxic", "trace", "track", "trade", "train", "trait",
        "tramp", "trawl", "tread", "treat", "trend", "trial", "tribe", "tried",
        "trill", "trout", "truce", "truck", "truly", "trump", "trunk", "truss",
        "trust", "truth", "tulip", "tuner", "tunic", "tutor", "tying", "ulcer",
        "uncle", "under", "unfit", "union", "until", "upper", "upset", "urban",
        "usage", "usher", "utter", "vague", "valid", "value", "valve", "vapour",
        "vault", "vicar", "video", "vigil", "vigour", "villa", "viola", "viper",
        "virgo", "virus", "visor", "vista", "vital", "vivid", "vixen", "voice",
        "vouch", "vying", "wader", "wafer", "waltz", "watch", "water", "weave",
        "wedge", "weigh", "weird", "whale", "wheat", "wheel", "where", "which",
        "while", "white", "whole", "whose", "widow", "witch", "woman", "women",
        "world", "worry", "worse", "worst", "worth", "would", "wound", "wrath",
        "wrist", "wrote", "yacht", "yearn", "yield", "young", "youth", "zebra"
    };

    // Hard: longer words a slightly older student should know
    static const std::vector<std::string> HARD = {
        "accent", "access", "action", "actual", "advise", "afford", "afraid",
        "agency", "agenda", "alight", "alpine", "ambush", "anchor", "anneal",
        "annual", "antler", "appear", "armour", "arrest", "arrive", "aspire",
        "assent", "assess", "asylum", "attach", "attend", "autumn", "avenue",
        "avouch", "awhile", "babble", "backed", "banter", "battle", "beacon",
        "beaten", "beauty", "beetle", "before", "behave", "belief", "belong",
        "bestow", "betray", "beware", "beyond", "blight", "blouse", "bonnet",
        "bottle", "bought", "bounce", "bounty", "breath", "bridge", "bright",
        "brooch", "bronze", "bureau", "butter", "button", "cactus", "camera",
        "candle", "canopy", "castle", "cattle", "caught", "cavern", "centre",
        "cereal", "change", "chapel", "charge", "chorus", "chrome", "circle",
        "citrus", "clench", "clever", "client", "climat", "cobalt", "cobble",
        "colour", "column", "combat", "comet", "commit", "common", "compel",
        "comply", "copper", "corner", "corona", "costly", "cotton", "couple",
        "cousin", "create", "credit", "crisis", "crispy", "curfew", "custom",
        "cutler", "dagger", "dancer", "danger", "darken", "deadly", "debate",
        "decamp", "decide", "decode", "decree", "defeat", "defend", "define",
        "degree", "delete", "demise", "deploy", "desert", "design", "detail",
        "detour", "device", "devote", "differ", "dimple", "direct", "divide",
        "dollar", "domain", "donate", "donkey", "double", "dragon", "drawl",
        "driven", "driver", "dryness", "dungeon", "during", "earthy", "editor",
        "effect", "effort", "either", "eldest", "empire", "enable", "encode",
        "endure", "enough", "ensure", "entire", "escape", "estate", "expand",
        "expert", "export", "expose", "fabric", "factor", "famine", "farmer",
        "father", "feline", "fellow", "female", "fender", "filter", "finale",
        "finger", "finish", "fiscal", "flight", "flinch", "flower", "flying",
        "follow", "forest", "formal", "foster", "fright", "frozen", "future",
        "gadget", "gallop", "garden", "gather", "gentle", "gibbon", "ginger",
        "giving", "glider", "global", "goblin", "golden", "govern", "gravel",
        "gravel", "grease", "greedy", "grieve", "ground", "growth", "grumpy",
        "grunge", "guitar", "gunner", "hammer", "handle", "happen", "harbour",
        "hardly", "hatred", "healer", "health", "height", "herald", "hidden",
        "hinder", "holder", "hollow", "honour", "horror", "hunter", "hurdle",
        "hustle", "ignore", "impact", "import", "impose", "inland", "insect",
        "insist", "intend", "invent", "invest", "invite", "island", "itself",
        "jigsaw", "jockey", "jostle", "juggle", "jumble", "jungle", "junior",
        "jacket", "kidney", "kitten", "knight", "labyrinth", "ladder", "lagoon",
        "lantern", "larder", "launch", "lavish", "lawful", "layout", "league",
        "legend", "lender", "length", "lesson", "lessen", "letter", "likely",
        "listen", "litter", "little", "living", "lizard", "locket", "lonely",
        "longer", "lovely", "lumber", "magnet", "maiden", "manner", "marble",
        "margin", "market", "marvel", "master", "matter", "meadow", "mellow",
        "member", "memoir", "mender", "menace", "middle", "mirror", "mister",
        "mobile", "modest", "module", "moment", "monkey", "mortal", "mother",
        "motion", "motive", "mottled", "murky", "muscle", "mutual", "mutter",
        "narrow", "nation", "nature", "needle", "nettle", "nickel", "nobody",
        "normal", "notice", "nought", "number", "nurtured", "nuzzle", "object",
        "oblige", "obtain", "offend", "offset", "office", "orange", "origin",
        "outlaw", "output", "outrun", "pallet", "parcel", "pardon", "patrol",
        "pebble", "pencil", "permit", "person", "pillar", "pirate", "plenty",
        "plight", "plover", "pocket", "poison", "police", "policy", "polite",
        "portal", "potter", "prefer", "pretty", "priest", "prince", "prison",
        "profit", "proper", "puddle", "purple", "puzzle", "quaint", "quarry",
        "rabbit", "racket", "random", "rather", "reason", "record", "reduce",
        "reform", "refuse", "region", "remain", "remind", "remote", "repair",
        "repeat", "rescue", "return", "reveal", "ribbon", "riddle", "rising",
        "ritual", "rocket", "rugged", "runner", "rustle", "saddle", "salmon",
        "sample", "savage", "saving", "scaffolding", "school", "scorch",
        "secure", "settle", "severe", "shadow", "shiver", "shrine", "silver",
        "simple", "single", "sister", "sleepy", "slight", "smooth", "socket",
        "solemn", "sorrow", "source", "spider", "sponge", "spring", "sprite",
        "square", "stable", "statue", "steady", "stolen", "strait", "strand",
        "stream", "stride", "string", "strong", "struck", "stuffy", "submit",
        "subtle", "suffer", "summit", "summer", "supply", "surely", "surgeon",
        "switch", "symbol", "system", "tartan", "tavern", "temple", "tender",
        "thanks", "theory", "throat", "thrown", "tightly", "timber", "tissue",
        "tongue", "travel", "trickle", "triple", "trivial", "trowel", "trudge",
        "tumble", "tunnel", "turtle", "twelve", "twenty", "twitch", "unfair",
        "unique", "unless", "unload", "unlike", "update", "useful", "vacant",
        "vanish", "velvet", "verify", "victor", "village", "violet", "virtue",
        "voyage", "wander", "warmer", "warren", "weaken", "wealth", "weapon",
        "whether", "wicked", "widgeon", "willow", "window", "winner", "winter",
        "wisdom", "wooden", "woolly", "worthy", "wreath", "wriggle", "yearly",
        "yellow", "zealot"
    };
}